### ISSUE TITLE
The default deploy-interface for sdflex-redfish driver is changed from "direct" to "sdflex-redfish" in stable/ussuri

### ISSUE THREAD

**Issue by agarwalnisha1980** [HewlettPackard/sdflex-ironic-driver#1]
The default deploy-interface for sdflex-redfish driver is changed from "direct" to "sdflex-redfish" in stable/ussuri. This is a compatibility break in the upgrade use case from stable/train release to  stable/ussuri.

**Comment by mallikarjuna-kolagatla** [comment]
Bug has been fixed in the sdflex-redfish driver version 1.2.1 for stable/ussuri release
